### PR TITLE
Additions to simplify wp_get_attachment_image_sizes internals

### PR DESCRIPTION
**Pull request by jaspermdegroot**
This PR contains what is left of #7 after #8.

### CODE REVIEW

**Comment by joemcgill** [comment]
I failed to push a few changes back to this repo while creating the patch for [34379](https://core.trac.wordpress.org/ticket/34379). Everything should be back in sync now, but it looks like there are conflicts to resolve.

**Comment by jaspermdegroot** [comment]
Ah ok, I assumed the patch was the same as the code in your 'sizes2' branch. Should have checked first.
At first glance it looks like everything is in there already, except one thing. In 10152a4 I also made `wp_get_attachment_image` check if both `srcset` and `sizes` values are being returned before setting anything. To prevent we set `srcset` but no `sizes`. This was not in my PR #7 yet.
I will do some rebasing.

**Comment by jaspermdegroot** [comment]
I think I did something wrong while rebasing. I don't feel like fixing it so I am going to close this PR and will checkout the 'sizes2' branch to see if I still see issues. If so, I will open a new PR for that.

**Comment by jaspermdegroot** [comment]
@joemcgill 

Actually the problem was already there in the 'sizes2' branch. You might want to do an interactive rebase onto master.

**Pull request closed without merging**
