### PR TITLE
WP #21819 – Hide cropped header images

### PR DESCRIPTION
**Pull request by joemcgill**
This branch is a WIP branch to experiment with an approach for minimizing the number of superfluous crops that end up in the media library when experimenting with different crops of the same image.

See: https://core.trac.wordpress.org/ticket/21819

### CODE REVIEW

**Comment by joemcgill** [comment]
So far, this tackles 2/3 of the problem:

1. Ensures only one crop exists for each base image.
2. Removes old crops from the "previous header images" list in the customizer.

The final piece of the puzzle is to hide all attachments created in the header image context from the regular media library.

Current implementation makes use of a new post meta key to track the base image each crop is created from. We might want to consider saving this as data to the regular attachment metadata array or by making use of the native `post_parent` field of the attachment.

**Comment by joemcgill** [comment]
@westonruter any chance you could help set up a preview sandbox from this PR?

**Comment by westonruter** [comment]
@joemcgill absolutely. Sandbox environment set up: http://trac-21819-xwp-testbed.pantheonsite.io/

**Comment by joemcgill** [comment]
Closed in favor of #24

**Pull request closed without merging**
